### ISSUE TITLE
(bug) Percentages don't add up

### ISSUE THREAD

**Issue by victormihalache** [dk949/ProjInfo#2]
<img width="473" alt="Screenshot 2022-03-16 at 9 35 55 AM" src="https://user-images.githubusercontent.com/82441538/158550362-b8da0f8b-b61f-4c8c-a050-62a74c6dd996.png">

Don't have much to add, except that this is a project made with `cardo new` and i made a build.

**Comment by dk949** [comment]
By default only the languages in the `Programming` category are displayed. But the percentage is calculated based on all files which have not been ignored. I can add a `Not shown` section to the output to maybe make this clearer.

**Comment by victormihalache** [comment]
That or add a `Other` count, where non-programming files go

**Comment by dk949** [comment]
[b4daf23](https://github.com/dk949/ProjInfo/commit/b4daf23eeba0848a629a054994ee6fae4f25389a) should solve it.
